global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['172.17.0.1:9100']

remote_write:
  - url: [REPLACE WITH YOUR GRAFANA URL]
    basic_auth:
      username: [REPLACE WITH YOUR GRAFANA USER ID]
      password: [REPLACE WITH YOUR GRAFANA PASSWORD]